CREATE SEQUENCE IF NOT EXISTS SEQ_SUBSET_ROWID;
CREATE TABLE IF NOT EXISTS SUBSET (
    SUBSET_ROWID          INTEGER DEFAULT nextval('SEQ_SUBSET_ROWID'),
    SUBSET_ID             VARCHAR(255) NOT NULL,
    VERSION               VARCHAR(3) NOT NULL,
    JSON_CONTENT          VARCHAR(25000)
);